services:
  postgres:
    container_name: postgres-b3-fetcher
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=b3-data-fetcher
    ports:
      - "5432:5432"
    restart: always


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=guest
    ports:
      - "5050:80"
    restart: always
