"""creating-fii-history

Revision ID: f4d30db06c30
Revises:
Create Date: 2025-10-31 19:56:07.521966

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4d30db06c30"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fiis",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cnpj", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("segment", sa.String(), nullable=True),
        sa.Column("management_type", sa.String(), nullable=True),
        sa.Column("administrator", sa.String(), nullable=True),
        sa.Column("target_audience", sa.String(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("isin_code", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fiis_cnpj"), "fiis", ["cnpj"], unique=True)
    op.create_index(op.f("ix_fiis_ticker"), "fiis", ["ticker"], unique=True)
    op.create_table(
        "fii_financial_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fii_id", sa.UUID(), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("net_worth", sa.Float(), nullable=True),
        sa.Column("issued_shares", sa.Float(), nullable=True),
        sa.Column("book_value_per_share", sa.Float(), nullable=True),
        sa.Column("monthly_dividend_yield", sa.Float(), nullable=True),
        sa.Column("monthly_equity_return", sa.Float(), nullable=True),
        sa.Column("monthly_effective_return", sa.Float(), nullable=True),
        sa.Column("amortization_per_share", sa.Float(), nullable=True),
        sa.Column("total_investors", sa.Integer(), nullable=True),
        sa.Column("total_liabilities", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["fii_id"], ["fiis.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fii_id", "reference_date", name="_fii_date_uc"),
    )
    op.create_index(
        op.f("ix_fii_financial_history_reference_date"),
        "fii_financial_history",
        ["reference_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_fii_financial_history_reference_date"),
        table_name="fii_financial_history",
    )
    op.drop_table("fii_financial_history")
    op.drop_index(op.f("ix_fiis_ticker"), table_name="fiis")
    op.drop_index(op.f("ix_fiis_cnpj"), table_name="fiis")
    op.drop_table("fiis")
    # ### end Alembic commands ###
